name: CI
on:
  push:
    branches: [ FinalProject ]
  
jobs:
  Back:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: Back

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v2
       
      - name: Docker

        run: |
          docker-compose build 
          docker-compose up -d

  Front:
      runs-on: ubuntu-latest
      defaults:
          run:
            working-directory: Front

      steps:
        - name: Checkout ğŸ›ï¸
          uses: actions/checkout@master

        - name: Install ğŸ”§
          run: npm install

        - name: Build ğŸ—ï¸
          run: npm run build

        - name: Test ğŸš¨
          run: npm test
